version: '3.7'
services:

  proxy:
    image: envoyproxy/envoy-alpine:v1.14.5
    environment:
      NODE_ENV: development
    ports:
      - 8081:8081
      - 8082:8082
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    network_mode: "host"
